### ISSUE TITLE
Invalid argument

### ISSUE THREAD

**Issue by dobcrypto** [BlockchainFor/ESBC2#2]
EXCEPTION: N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_16bad_lexical_castEEEEE       
bad lexical cast: source type value could not be interpreted as target       
C:\ESBC\esbcoin-qt.exe in Runaway exception       

2019-04-26 17:24:51 CDBEnv::EnvShutdown : Error 22 shutting down database environment: Invalid argument
![esbc](https://user-images.githubusercontent.com/16653151/56825257-4d545680-6861-11e9-97fd-8c3c429c9b0c.PNG)

**Comment by SkaZun** [comment]
Check data in the **masternode.conf** file, note how the transaction index is specified.
And in the next release I will add more checks on the correctness of the source data.

**Comment by dobcrypto** [comment]
@SkaZun yeah, i found a "bug", it was not commented mn line in masternode.conf but why this crash start wallet i donno =(
